name: example
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.5.0
  flutter_json_view: ^1.1.5

  data_widgets:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.5.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
